const Theme = {
  icons: {
    loginLogo: require("../assets/img/loginLogo.png"),
    AppLogo: require("../assets/img/logo.png"),
    loginBgImg: require("../assets/img/loginBgImg.png"),
    map_marker: require("../assets/img/map-marker.png"),
    landing_image: require("../assets/img/landingImage.png"),
    chili_icon: require("../assets/img/chili.png"),
    clock_icon: require("../assets/img/clock.png"),
    fris_icon: require("../assets/img/fris.png"),
    service1: require("../assets/img/service1.png"),
    service2: require("../assets/img/service2.png"),
    service3: require("../assets/img/service3.png"),
    call_icon: require("../assets/img/call-icon.png"),
    user_avatar: require("../assets/img/user_avatar.png"),
    slider_icon1: require("../assets/img/slider1.jpg"),
    slider_icon2: require("../assets/img/slider2.jpg"),
    slider_icon3: require("../assets/img/slider3.jpg"),
    user_icon1: require("../assets/img/user1.jpeg"),
    user_icon2: require("../assets/img/user2.jpeg"),
    user_icon3: require("../assets/img/user3.jpeg"),
    bg1: require("../assets/img/bg1.png"),
  },
};
export default Theme;
